# Simple Queue Demo
#
# A minimal example showing periodic task generation and processing
# Usage: cargo run -- --rules examples/simple_queue/simple_queue.yaml

# Web UI settings
web_ui:
  enabled: true
  host: "localhost"
  base_port: 9990
  cols: 80
  rows: 24

# Agents configuration with triggers and rules
agents:
  pool: 1
  
  # External triggers - initiated by events
  triggers:
    # Generate tasks every 15 seconds
    - name: "generate_tasks"
      event: "timer:15s"
      action: "enqueue"
      queue: "tasks"
      command: "bash examples/simple_queue/list_tasks.sh"

    # Process each task automatically
    - name: "process_tasks"
      event: "queue:tasks"
      action: "send_keys"
      keys: ["bash examples/simple_queue/process_task.sh <task>", "\r"]

  # No rules needed for this simple example
  rules: []