# Simple Source Processing Demo
#
# A minimal example showing periodic task generation and processing using the new simplified format
# Usage: cargo run -- --config examples/simple_queue/config.yaml

# Web UI settings
web_ui:
  enabled: true
  host: "localhost"
  base_port: 9990
  cols: 80
  rows: 24

# Agents configuration with triggers and rules
agents:
  pool: 1
  
  # External triggers - initiated by events
  triggers:
    # Generate and process tasks every 15 seconds
    - name: "process_tasks"
      event: "timer:15s"
      source: "bash examples/simple_queue/list_tasks.sh"
      action: "send_keys"
      keys: ["bash examples/simple_queue/process_task.sh ${1}", "\r"]

  # No rules needed for this simple example
  rules: []