# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 75%
        threshold: 5%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 10%

  ignore:
    - "tests/"
    - "examples/"
    - "target/"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false