# ccauto configuration for monitoring GitHub issues
web_ui:
  enabled: true
  host: "localhost"
  base_port: 9990
  cols: 120
  rows: 40

agents:
  pool: 1
  
  # External triggers - periodic execution
  triggers:
    - name: "monitor_issues"
      event: "timer:10s"
      source: "bash list-issue.sh"
      dedupe: true
      action: "send_keys"
      keys: ["claude \"/solve ${1}\" --dangerously-skip-permissions", "\r"]

  # Automatic detection rules
  rules:      
    - when: "Successfully Resolved"
      action: "send_keys"
      keys: ["/exit", "\r"]

    - when: "Successfully completed issue"
      action: "send_keys"
      keys: ["/exit", "\r"]

    - when: "Issue #\\d+ Complete"
      action: "send_keys"
      keys: ["/exit", "\r"]

    - when: "✅ Issue #\\d+ -"
      action: "send_keys"
      keys: ["/exit", "\r"]

    - when: "Pull Request: https://github.com"
      action: "send_keys"
      keys: ["/exit", "\r"]
