# RuleAgents Default Configuration
#
# This is the default configuration file that demonstrates basic automation.
# For more examples, see the examples/ directory:
# - examples/basic/config.yaml - Basic pattern matching and on_start triggers
# - examples/simple_queue/simple_queue.yaml - Queue system with periodic triggers
# - examples/dedupe_queue/dedupe_example.yaml - Duplicate filtering queues
# - examples/agent_pool/concurrency_demo.yaml - Multiple agents running in parallel

# Optional monitor configuration
monitor:
  base_port: 9990        # First agent port (default: 9990)
  agent_pool_size: 1     # Number of parallel agents (default: 1)
  web_ui:
    enabled: true        # Enable/disable web interface
    host: "localhost"    # Bind address (use "0.0.0.0" for external access)

# External triggers - initiated by system events
entries:
  - name: "start_mock"
    trigger: "on_start"           # Automatic startup trigger
    action: "send_keys"
    keys: ["bash examples/basic/mock.sh", "\r"]

# Automatic detection rules - triggered by terminal state changes
# Higher priority = earlier in the list (line order matters)
rules:
  - pattern: "Do you want to proceed"    # Highest priority
    action: "send_keys"
    keys: ["1", "\r"]
    
  - pattern: "^exit$"                    # Lower priority
    action: "send_keys"
    keys: ["/exit", "\r"]