monitor:
  base_port: 3000
  agent_pool_size: 1

entries:
  - name: test_ls
    trigger: on_start
    action: send_keys
    keys: ["ls -la", "\r"]

rules:
  - pattern: "total"
    action: send_keys
    keys: ["echo", "Success!", "\r"]