# Example configuration with Web UI enabled
# This shows how to configure the web terminal interface

monitor:
  base_port: 9990        # First agent web interface port
  agent_pool_size: 2     # Multiple agents get sequential ports (9990, 9991)
  web_ui:
    enabled: true        # Enable/disable web interface
    host: "localhost"    # Bind address (use "0.0.0.0" for external access)
    theme: "default"     # UI theme selection (for future use)

# Example entries for automation
entries:
  - name: "compound_command_test"
    trigger: "on_start"
    action: "send_keys"
    keys: ["echo 'First message'; echo 'Second message'; pwd; ls -la; echo 'Final message'", "\r"]

# Example rules for pattern matching
rules:
  - pattern: "Web UI ready"
    action: "send_keys"
    keys: ["echo 'UI is ready'", "\r"]