# Example configuration with Web UI enabled
# This shows how to configure the web terminal interface

# Web UI configuration
web_ui:
  enabled: true          # Enable/disable web interface
  host: "localhost"      # Bind address (use "0.0.0.0" for external access)
  base_port: 9990        # First agent web interface port
  cols: 120              # Terminal width for all agents
  rows: 40               # Terminal height for all agents

# Agent configuration with triggers and rules
agents:
  pool: 2                # Number of agents (get sequential ports: 9990, 9991)
  
  # External triggers - initiated by events
  triggers:
    - name: "compound_command_test"
      event: "startup"
      action: "send_keys"
      keys: ["ls --color=always", "\r"]

  # Automatic detection rules
  rules:
    - when: "Web UI ready"
      action: "send_keys"
      keys: ["echo 'UI is ready'", "\r"]