# Example configuration with Web UI enabled
# This shows how to configure the web terminal interface

# Web UI configuration - includes terminal display settings
web_ui:
  enabled: true          # Enable/disable web interface
  host: "localhost"      # Bind address (use "0.0.0.0" for external access)
  base_port: 9990        # First agent web interface port
  cols: 120              # Terminal width for all agents
  rows: 40               # Terminal height for all agents

# Agent configuration and automation
agents:
  pool: 2                # Number of agents (get sequential ports: 9990, 9991)
  
  # Example triggers for automation
  triggers:
    - name: "compound_command_test"
      event: "startup"
      action: "send_keys"
      keys: ["ls --color=always", "\r"]

  # Example rules for pattern matching
  rules:
    - when: "Web UI ready"
      action: "send_keys"
      keys: ["echo 'UI is ready'", "\r"]