# Simplified Source Processing with Deduplication Example
# 
# This example demonstrates the new simplified source processing functionality:
# 1. Periodic triggers that execute source commands at intervals
# 2. Direct processing of each line from source command output
# 3. Optional deduplication prevents duplicate processing
# 4. Unified ${1} placeholder syntax for variable expansion
#
# Usage: cargo run -- --config examples/dedupe_queue/config.yaml

# Web UI settings
web_ui:
  enabled: true
  host: "localhost"
  base_port: 9990
  cols: 80
  rows: 24

# Agents configuration with triggers and rules
agents:
  pool: 1
  
  # External triggers - initiated by events
  triggers:
    # 1. Periodic Item Generation with Deduplication
    # Executes generate_items.sh every 8 seconds and processes ONLY unique results
    - name: "process_unique_items"
      event: "timer:8s"
      source: "bash examples/dedupe_queue/generate_items.sh"
      dedupe: true
      action: "send_keys"
      keys: ["echo 'Processing unique: ${1}'", "\r", "bash examples/dedupe_queue/process_item.sh ${1}", "\r"]

  # Automatic detection rules
  rules:
    # 2. Capture and log completed items
    # When item processing shows "Status: processed", log completion
    - when: "Status: processed"
      action: "send_keys"
      keys: ["echo 'Item completed at: $(date)'", "\r"]

    # 3. Capture Processed Items with Variables
    # Captures specific item IDs from output and logs them
    - when: "Processing unique item: (item-\\d+)"
      action: "send_keys"
      keys: ["echo 'Processed: ${1}'", "\r"]