# Configuration for agent automation with Claude

# Web UI configuration - includes display settings
web_ui:
  enabled: true
  host: "localhost"
  base_port: 9990
  cols: 120
  rows: 40

# Agent configuration and automation rules
agents:
  pool: 1  # Number of agents in the pool
  
  # Triggers monitored in Idle state
  triggers:
    - name: "claude"
      event: "startup"
      action: "send_keys"
      keys: ["claude 'say hello, in Japanese'", "\r"]
  
  # Rules monitored in Active state
  rules:
    - when: "Do you want to proceed"
      action: "send_keys"
      keys: ["1", "\r"]
      
    # Match Claude's response when it starts generating text
    - when: "こんにちは"
      action: "send_keys"
      keys: ["/exit", "\r"]