# Entry and Rule definitions for agent automation

# External triggers - initiated by user commands
entries:
  - name: "claude"
    trigger: "on_start"
    action: "send_keys"
    keys: ["claude 'say hello, in Japanese'", "\r"]

# Automatic detection rules - triggered by terminal state changes
# Higher priority = earlier in the list (line order matters)
rules:
  - pattern: "Do you want to proceed"
    action: "send_keys"
    keys: ["1", "\r"]
    
  # Match Claude's response when it starts generating text
  - pattern: "こんにちは|Hello"
    action: "send_keys"
    keys: ["q", "\r"]