# Entry and Rule definitions for agent automation

# Monitor configuration
monitor:
  base_port: 9990
  agent_pool_size: 1
  web_ui:
    enabled: true
    host: "localhost"
    theme: "default"
  # Agent configurations (optional - defaults to 80x24)
  agents:
    - name: "default"
      cols: 120
      rows: 40

# External triggers - initiated by user commands
entries:
  - name: "claude"
    trigger: "on_start"
    action: "send_keys"
    keys: ["claude 'say hello, in Japanese'", "\r"]

# Automatic detection rules - triggered by terminal state changes
# Higher priority = earlier in the list (line order matters)
rules:
  - pattern: "Do you want to proceed"
    action: "send_keys"
    keys: ["1", "\r"]
    
  # Match Claude's response when it starts generating text
  - pattern: "こんにちは"
    action: "send_keys"
    keys: ["/exit", "\r"]