# Agent Pool Example Configuration
# 
# This example demonstrates agent pool functionality:
# - 2 agents running in parallel on different ports  
# - Tasks distributed across available idle agents
#
# Usage: cargo run -- --config examples/agent_pool/config.yaml

# Web UI configuration
web_ui:
  enabled: true
  host: "localhost"
  base_port: 9990     # First agent on port 9990
  cols: 80
  rows: 24

# Agent configuration
agents:
  pool: 2      # 2 agents: 9990, 9991
  
  triggers:
    # Task A - will go to first available idle agent
    - name: "task_a"
      event: "timer:3s"
      action: "send_keys"
      keys: ["bash examples/agent_pool/simple_task.sh A", "\r"]

    # Task B - will go to first available idle agent  
    - name: "task_b"
      event: "timer:4s"
      action: "send_keys"
      keys: ["bash examples/agent_pool/simple_task.sh B", "\r"]

  rules:
    # React to task completion
    - when: "Task (\\w+) completed"
      action: "send_keys"
      keys: ["echo 'Acknowledged task ${1}'", "\r"]