# Agent Pool Example Configuration
# 
# This example demonstrates basic agent pool functionality:
# - 2 agents running in parallel on different ports
# - Simple tasks distributed across agents automatically
#
# Usage: cargo run -- --rules examples/agent_pool/concurrency_demo.yaml

# Web UI configuration
web_ui:
  enabled: true
  host: "localhost"
  base_port: 9990     # First agent on port 9990
  cols: 80
  rows: 24

# Agent configuration with triggers and rules
agents:
  pool: 2             # 2 agents: 9990, 9991
  
  # External triggers - initiated by events
  triggers:
    # Task A - periodic timer trigger
    - name: "task_a"
      event: "timer:3s"
      action: "send_keys"
      keys: ["bash examples/agent_pool/simple_task.sh A", "\r"]

    # Task B - periodic timer trigger
    - name: "task_b"
      event: "timer:4s"
      action: "send_keys"
      keys: ["bash examples/agent_pool/simple_task.sh B", "\r"]

  # Automatic detection rules
  rules:
    # React to task completion
    - when: "Task (\\w+) completed"
      action: "send_keys"
      keys: ["echo 'Acknowledged task ${1}'", "\r"]