# Configuration for agent automation

# Web UI settings
web_ui:
  enabled: true
  host: "localhost"
  base_port: 9990
  cols: 80
  rows: 24

# Agents configuration with triggers and rules
agents:
  pool: 1
  
  # External triggers - initiated by user commands or events
  triggers:
    - name: "start_mock"
      event: "startup"
      action: "send_keys"
      keys: ["bash examples/basic/mock.sh", "\r"]

  # Automatic detection rules - triggered by terminal state changes
  # Higher priority = earlier in the list (line order matters)
  rules:
    - when: "Do you want to proceed"
      action: "send_keys"
      keys: ["1", "\r"]
      
    - when: "^exit$"
      action: "send_keys"
      keys: ["/exit", "\r"]