# Basic agent automation configuration

# Web UI settings
web_ui:
  enabled: true
  host: "localhost"
  base_port: 9990
  cols: 80
  rows: 24

# Agent configuration and automation
agents:
  pool: 1
  
  # Triggers for starting automation
  triggers:
    - name: "start_mock"
      event: "startup"
      action: "send_keys"
      keys: ["bash examples/basic/mock.sh", "\r"]
  
  # Rules for responding to terminal output
  rules:
    - when: "Do you want to proceed"
      action: "send_keys"
      keys: ["1", "\r"]
      
    - when: "^exit$"
      action: "send_keys"
      keys: ["/exit", "\r"]